# Generated by Django 5.1.4 on 2025-01-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
